[programs.localnet]
kombt = "ELbd3fkvCeqDCrHdoZ2FLzCyo5jNynik2bLzpSFyGcqs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 sdk/typescript/tests/**/*.spec.ts"

[features]
seeds = false

# rev60

# rev70

# rev72

# rev80

# rev91

# rev94

# rev118

# rev133

# rev140

# rev166

# rev179

# rev183

# rev189

# rev193

# rev203

# rev207

# rev231

# rev235

# rev248

# rev254

# rev265

# rev279
