edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"

# rev12

# rev15

# rev39

# rev48

# rev49

# rev50

# rev65

# rev67

# rev69

# rev71

# rev115

# rev120

# rev127

# rev166

# rev180

# rev249

# rev294

# rev295

# rev299
